[tool.poetry]
name = "Kita_bot"
version = "0.1"
description = ""
authors = ["Criss"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
numpy = "^1.22.2"
replit = "^3.2.4"
Flask = "^2.2.0"
urllib3 = "^1.26.12"
yfinance = "^0.1.87"
telebot = "^0.0.4"
pyTelegramBotAPI = "^4.7.1"
pyTelegramBotAPI-markups = "^0.0.4"

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = {extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"